language: python
python:
    - "3.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codeclimate-test-reporter

services:
    - postgresql

before_script:
    - psql -c "CREATE ROLE prince WITH SUPERUSER LOGIN PASSWORD 'prince';" -U postgres
    - psql -c "CREATE DATABASE hello_books;" -U postgres

script:
    - nosetests --with-coverage

after_success:
    - coveralls
    - codeclimate-test-reporter 