language: python

python:
    - 3.7

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

install: source build_tools/travis/install.sh

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
        branch: ZaylonBranch
